name: Update PyHC Package Submodules

on:
  schedule:
    # Run daily at midnight Mountain Time (06:00 UTC during MDT, 07:00 UTC during MST)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger from Actions tab

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update all submodules to latest
        run: |
          git submodule update --remote

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update PyHC packages to latest versions [automated]

          Updated on: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push

      - name: No updates needed
        if: steps.check_changes.outputs.has_changes == 'false'
        run: echo "All submodules are already up to date"
