name: Update PyHC Package Submodules

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger from Actions tab

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update all submodules to latest
        run: |
          # Update each submodule to the latest commit on its tracked branch
          git submodule foreach '
            # Get the default branch (usually main or master)
            default_branch=$(git remote show origin | grep "HEAD branch" | cut -d ":" -f 2 | xargs)
            echo "Updating $name to latest $default_branch..."
            git checkout $default_branch 2>/dev/null || git checkout main 2>/dev/null || git checkout master
            git pull origin $default_branch || git pull origin main || git pull origin master
          '
          # Stage all submodule updates
          git add pyhc_packages/

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update PyHC packages to latest versions [automated]

          Updated on: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push

      - name: No updates needed
        if: steps.check_changes.outputs.has_changes == 'false'
        run: echo "All submodules are already up to date"
